# Generated by Django 2.0.5 on 2018-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180520_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
    ]
