# Generated by Django 2.0.5 on 2018-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showme',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='showme',
            name='title',
            field=models.CharField(default='title', max_length=10),
        ),
        migrations.AlterField(
            model_name='showme',
            name='description',
            field=models.CharField(default='add a description', max_length=100),
        ),
    ]
